version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:12.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kry}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-4321}
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-emrecaliskan17@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-4321}
    volumes:
       - ./data/pgadmin:/var/lib/pgmadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

