version: '2.0'

services:
  postgresql:
    image: postgres:11
    ports:
      - "5431:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=kry
      - POSTGRES_PASSWORD=4321
      - POSTGRES_DB=kry


